@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title КиноБездна - целевая архитектура

Person(user, "Пользователь", "смотрит кино, платит за подписку")

System_Ext(rec, "Рекомендации", "внешняя система подборки фильмов")

System_Boundary(cinema, "КиноБездна") {

    Container(proxy, "Proxy", "C# .NET", "роутит трафик, фиче-флаг для постепенной миграции")

    Container(monolith, "Монолит", "Go", "пользователи, платежи, подписки, фильмы")

    Container(movies, "Movies Service", "Go", "метаданные фильмов")

    Container(events, "Events Service", "C# .NET", "события через кафку")

    Container(kafka, "Kafka", "kafka", "очередь сообщений")

    ContainerDb(db, "PostgreSQL", "Database", "одна база для всех")
}

Rel(user, proxy, "HTTP")
Rel(proxy, monolith, "если флаг выключен", "HTTP")
Rel(proxy, movies, "если флаг включён", "HTTP")
Rel(proxy, events, "события", "HTTP")
Rel(monolith, db, "SQL")
Rel(movies, db, "SQL")
Rel(events, kafka, "produce/consume")
Rel(monolith, rec, "async HTTP")

@enduml